=== paohaijiao/jquick-curl/src/main/resources/paohaijiao/dtd/Jquick-curl.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT curls (curl*)>
        <!ATTLIST curls namespace CDATA #REQUIRED>
        <!ELEMENT curl (#PCDATA | if | foreach | choose)*>
        <!ATTLIST curl
                name CDATA #REQUIRED
                returnClass CDATA #REQUIRED
                >
        <!ELEMENT if (#PCDATA | if | foreach | choose)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >
        <!ELEMENT foreach (#PCDATA | if | foreach | choose)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #REQUIRED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT choose (when*, otherwise?)>
        <!ATTLIST choose
                xmlns CDATA #IMPLIED
                >
        <!ELEMENT when (#PCDATA | if | foreach | choose)*>
        <!ATTLIST when
                test CDATA #REQUIRED
                >
        <!ELEMENT otherwise (#PCDATA | if | foreach | choose)*>

=== paohaijiao/jquick-curl/src/main/resources/apis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curls PUBLIC "-//PAOHAIJIAO//DTD API CURL 1.0//EN"
        "classpath:paohaijiao/dtd/Jquick-curl.dtd">
<curls namespace="com.github.paohaijiao.test.xml.UserApi">
    <curl name="all" returnClass="java.util.List">
        curl -X GET --location 'http://localhost:8080/api/users/all'
    </curl>

    <curl name="getUserById" returnClass="com.github.paohaijiao.test.model.JUser">
        curl -X GET http://localhost:8080/api/users/1
    </curl>
    <curl name="getUserByIdVariable" returnClass="com.github.paohaijiao.test.model.JUser">
        curl -X GET #{host} \
        <if test="a==1"> -H "Content-Type: application/json" </if>
    </curl>

    <curl name="users" returnClass="com.github.paohaijiao.test.model.JUser">
        curl -X POST http://localhost:8080/api/users/createUser \
        -H "Content-Type: application/json" \
        -d '{"name":"John Doe","email":"john@example.com"}'
    </curl>
    <curl name="usersByVariable" returnClass="com.github.paohaijiao.test.model.JUser">
        curl -X POST http://localhost:8080/api/users/createUser \
        -H "Content-Type: application/json" \
        -d '{"name":#{name},"email":#{email}}'
    </curl>

    <curl name="usersPut" returnClass="com.github.paohaijiao.test.model.JUser">
        curl -X PUT http://localhost:8080/api/users/1 \
        -H "Content-Type: application/json" \
        -d '{"name":"John Doe Updated","email":"john.updated@example.com"}'
    </curl>

    <curl name="usersPatch" returnClass="com.github.paohaijiao.test.model.JUser">
        curl -X PATCH http://localhost:8080/api/users/1 \
        -H "Content-Type: application/json" \
        -d '{"name":"John Doe Patched"}'
    </curl>

    <curl name="usersDelete" returnClass="java.lang.Void">
        curl -X DELETE http://localhost:8080/api/users/1
    </curl>

    <curl name="usersHead" returnClass="java.lang.Void">
        curl -X HEAD -I http://localhost:8080/api/users/1
    </curl>

    <curl name="usersOptions" returnClass="com.github.paohaijiao.model.JResult">
        curl -X OPTIONS http://localhost:8080/api/users/1
    </curl>

    <curl name="usersTrace" returnClass="java.lang.String">
        curl -X TRACE http://localhost:8080/api/users/trace \
        -H "Content-Type: text/plain" \
        -d "This is a trace request body"
    </curl>

    <curl name="upload" returnClass="java.lang.String">
        curl -X POST http://localhost:8080/api/users/upload \
        -F "file=@D:\test\pie.xlsx"
    </curl>

    <curl name="upload1" returnClass="java.lang.String">
        curl -X POST http://localhost:8080/api/users/upload-multiple \
        -F "files=@D:\test\pie.xlsx" \
        -F "files=@D:\test\pie2.xlsx"
    </curl>

    <curl name="download" returnClass="byte[]">
        curl -X GET http://localhost:8080/api/users/download/pie.xlsx \
        --output 'd://test//pie3.xlsx'
    </curl>

    <curl name="uploadWithPostParams" returnClass="java.lang.String">
        curl -X POST http://localhost:8080/api/users/upload-with-params \
        -F "userId=123" \
        -F "username=john" \
        -F "file=@D:\test\pie3.xlsx"
    </curl>
</curls>
